// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKcXT59g09c4f2iQERatAF4QB_1J1hb4',
    appId: '1:364021400399:android:911b3984aea84f1a537b3a',
    messagingSenderId: '364021400399',
    projectId: 'organiser-dcd2c',
    databaseURL: 'https://organiser-dcd2c-default-rtdb.firebaseio.com',
    storageBucket: 'organiser-dcd2c.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpeQhbPU2EKfFW2D10gpBWv833onY2mw',
    appId: '1:364021400399:web:ee743668c988866a537b3a',
    messagingSenderId: '364021400399',
    projectId: 'organiser-dcd2c',
    authDomain: 'organiser-dcd2c.firebaseapp.com',
    databaseURL: 'https://organiser-dcd2c-default-rtdb.firebaseio.com',
    storageBucket: 'organiser-dcd2c.appspot.com',
    measurementId: 'G-19KLSHS2PN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpLHCYFHfuPR8W6GhUavPp4HzbZyvoJsc',
    appId: '1:364021400399:ios:f5a70f0333cfb48a537b3a',
    messagingSenderId: '364021400399',
    projectId: 'organiser-dcd2c',
    databaseURL: 'https://organiser-dcd2c-default-rtdb.firebaseio.com',
    storageBucket: 'organiser-dcd2c.appspot.com',
    iosClientId: '364021400399-qcu4effod32a5kjddqmhju56qte54bg1.apps.googleusercontent.com',
    iosBundleId: 'com.oganiser.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpLHCYFHfuPR8W6GhUavPp4HzbZyvoJsc',
    appId: '1:364021400399:ios:013e6042a2bc602d537b3a',
    messagingSenderId: '364021400399',
    projectId: 'organiser-dcd2c',
    databaseURL: 'https://organiser-dcd2c-default-rtdb.firebaseio.com',
    storageBucket: 'organiser-dcd2c.appspot.com',
    iosClientId: '364021400399-pto8jbv72bf0knq2t0dlqcpr6osh0qtv.apps.googleusercontent.com',
    iosBundleId: 'com.organiser.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQpeQhbPU2EKfFW2D10gpBWv833onY2mw',
    appId: '1:364021400399:web:7d99003a351fc6fa537b3a',
    messagingSenderId: '364021400399',
    projectId: 'organiser-dcd2c',
    authDomain: 'organiser-dcd2c.firebaseapp.com',
    databaseURL: 'https://organiser-dcd2c-default-rtdb.firebaseio.com',
    storageBucket: 'organiser-dcd2c.appspot.com',
    measurementId: 'G-8F0TH91RZH',
  );

}